# Form implementation generated from reading ui file 'YTTRDBAddVideoDlg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(405, 239)
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(40, 100, 351, 71))
        self.textEdit.setObjectName("textEdit")
        self.pushButtonOK = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonOK.setEnabled(False)
        self.pushButtonOK.setGeometry(QtCore.QRect(40, 190, 75, 31))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.pushButtonCancel = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonCancel.setGeometry(QtCore.QRect(130, 190, 75, 31))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 331, 41))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Video"))
        self.pushButtonOK.setText(_translate("Dialog", "OK"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Youtube video id, video URL or playlist URL"))
